### ISSUE TITLE
couldn't reach the MetaGrid projects API service and are working on it

### ISSUE THREAD

**Issue by yu900** [esgf2-us/metagrid#640]
![屏幕截图 2024-05-20 224320](https://github.com/esgf2-us/metagrid/assets/140364554/40ee8ed4-e40a-4394-a02e-4bcc217a7926)
### Describe the bug

**Desktop (please complete the following information):**

- OS:

- Browser and Version:

#### To Reproduce

1.

**Comment by sashakames** [comment]
Intermittent issue

**Comment by anikfal** [comment]
@sashakames
Could you inform me which components of Metagrid are involved in this issue so that I can have a chance to troubleshoot my own installation?
I'd also like to know if the "_MetaGrid Projects API Service_" is a repository ready to be deployed, or if it's something I need to build from scratch myself?

**Comment by sashakames** [comment]
@anikfal  The projects API is part of the backend.  I see that you posted to our Slack and have communicated with Zach.  Jason B. at LLNL has also deployed Kubernetes.  We could check if he had a similar problem at some point.  I saw something about CORS.  The frontend running in the browser needs to communicate with the backend directly through the same ingress host but a different route/path.
Also Katharina B manages the CDNOT list and the meeting invites so you can join the monthly site operations call to discuss your problems with deployment there.
